version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./backend
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "create-drop",
        "spring.logging.level.org.hibernate.SQL" : "debug",
        "spring.jpa.show-sql" : "true",
        "spring.mvc.hiddenmethod.filter.enabled" : "true",
        "spring.mail.host" : "...",
        "spring.mail.port" : "...",
        "spring.mail.username" : "...",
        "spring.mail.password" : "...",
        "spring.mail.properties.mail.smtp.auth" : "true",
        "spring.mail.properties.mail.smtp.starttls.enable" : "true",
        "spring.servlet.multipart.max-file-size" : "50MB",
        "spring.servlet.multipart.max-request-size" : "50MB",
        "spring.config.import" : "optional:file:.env[.properties]",
        "secret-key" : "..."
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: